version: 1.0.{build}
image: Ubuntu2004
environment:
  nodejs_version: "18"

install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - nvm install $nodejs_version
  - nvm use $nodejs_version
  
  # Установка Yarn и зависимостей
  - npm install -g yarn
  - yarn install

build_script:
  - yarn run build
  - ls -R dist  # Проверка содержимого папки dist

on_success:
  - git config --global user.email "appveyor@example.com"
  - git config --global user.name "Appveyor CI"
  - git remote set-url origin https://$GITHUB_TOKEN@github.com/Niklles/ahj-dnd.git
  - yarn deploy